FROM python:3.9-slim

WORKDIR /app

RUN pip install --no-cache-dir flask flask-sqlalchemy flask-cors mysql-connector-python requests python-consul

COPY frontend/ /app/

EXPOSE 5001

CMD ["python", "run.py"]
