FROM python:3.9-slim

WORKDIR /app

RUN pip install --no-cache-dir flask flask-sqlalchemy flask-cors mysql-connector-python python-consul requests pymysql cryptography

COPY microUsers/ /app/

EXPOSE 5002

CMD ["python", "run.py"]
